name: Build EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install PyInstaller
      run: pip install pyinstaller
    - name: Pack EXE
      run: pyinstaller --onefile --console main.py
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: myapp-exe
        path: dist/*.exe
